feat(theme): update cards primary color
bonitasoft/bonita-documentation-theme pull request #6
Opened 2020-12-11 16:38 UTC by benjaminParisel

2020-12-15 16:38 UTC, benjaminParisel commented
To display card as follow 

![image](https://user-images.githubusercontent.com/25297128/102244053-221def80-3efc-11eb-9d3f-0876355da34c.png)

You need, in your adoc document used this synthax:
`[.card-section]
== Highlight

[.card.card-index]
--
yourURLOrLinkToOtherFile[[.card-title]#YourTitleHere# [.card-body]#pass:q[A little summary here]#]
--`

2020-12-16 14:28 UTC, alachambre requested changes

2020-12-16 14:28 UTC, alachambre commented on preview-src/index.adoc
> +//--
Remove useless comment pls

2020-12-16 14:43 UTC, alachambre approved these changes

2020-12-16 14:44 UTC, merged