feat: improve troubleshooting section
bonitasoft/bonita-documentation-theme pull request #85
Opened 2022-03-25 16:08 UTC by benjaminParisel

2022-03-25 16:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-documentation-theme?pullRequest=85) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-documentation-theme?pullRequest=85) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: benjaminParisel<br/>:x: Adrien<br/><hr/>**Adrien** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-documentation-theme?pullRequest=85) it.</sub>

2022-03-31 15:18 UTC, benjaminParisel commented
what is missing:
- [ ]  icon just after anchor Troubleshooting
![image](https://user-images.githubusercontent.com/25297128/161090471-1fe7844e-0686-4f41-8b63-f7e35007b873.png)

- [ ] if user put another title after troubleshooting-title. The icon is display too => We don't want it.. check if it's right

2022-04-08 14:12 UTC, benjaminParisel commented
based on #88

2022-04-15 08:01 UTC, jeromecambon requested changes

2022-04-15 08:01 UTC, jeromecambon commented on src/stylesheets/globals/vars.scss
> +  --color-troobleshooting-border: var(--color-admonition-important-bg);
duplicated var --color-troobleshooting-border. Remove this one.

2022-04-15 08:01 UTC, jeromecambon commented on src/stylesheets/globals/vars.scss
> +  --color-troobleshooting-border: #f5c80071;
typo (tr**oo**bleshooting)

2022-04-15 09:24 UTC, jeromecambon approved these changes
LGTM!

2022-04-15 09:26 UTC, merged